### ISSUE TITLE
didn't setup localizations, and it crashed

### ISSUE THREAD

**Issue by sgehrman** [Mosc/relative_time#1]
The following TypeErrorImpl was thrown building StreamBuilder<SubscriptionStateModel>(dirty,
dependencies: [_LocalizationsScope-[GlobalKey#6f1c4]], state:
_StreamBuilderBaseState<SubscriptionStateModel, AsyncSnapshot<SubscriptionStateModel>>#bf5ab):
Unexpected null value.
The relevant error-causing widget was:
  StreamBuilder<SubscriptionStateModel>
StreamBuilder:file:///home/steve/Documents/GitHub/dfc/chargebee_server/lib/shop_widget/dashboard_panel/charges/charges_card.dart:160:12
lib/…/charges/charges_card.dart:160
When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49            throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 528:63        nullCheck
packages/relative_time/src/l10n/relative_time_localizations.dart 183:44                 of
packages/relative_time/src/relative_time.dart 47:37                                     format
packages/dfc_flutter/src/utils/dates.dart 36:16                                         relativeDateString
packages/chargebee_server/shop_widget/dashboard_panel/charges/charges_card.dart 177:27  <fn>

**Comment by Mosc** [comment]
Hey. Wouldn't that be the expected result though, if you didn't perform the setup? The `RelativeTime.locale` constructor is more appropriate in that case. Or are you saying that the exception occurs even when using the non-`BuildContext`-based constructor?
