### ISSUE TITLE
Relative to custom date

### ISSUE THREAD

**Issue by westito** [Mosc/relative_time#2]
There is no option to use custom date instead of current time

**Comment by DanielMoscoviterAH** [comment]
Hey. I'd love to know what use case you have for that. Doesn't "tomorrow" or "5 days ago" only make sense relative to the current time?

One way to use a custom time without an explicit option in relative_time would be to make use of [clock](https://pub.dev/packages/clock). That should allow you to "mock" the current time with any `DateTime`:

```dart
withClock(
  Clock.fixed(DateTime.parse("2012-02-27")),
  () => RelativeTime(context).format(time),
);
```

**Comment by Mosc** [comment]
Hey. I'd love to know what use case you have for that. Doesn't "tomorrow" or "5 days ago" only make sense relative to the current time?

One way to use a custom time without an explicit option in relative_time would be to make use of [clock](https://pub.dev/packages/clock). That should allow you to "mock" the current time with any `DateTime`:

```dart
withClock(
  Clock.fixed(DateTime.parse("2012-02-27")),
  () => RelativeTime(context).format(time),
);
```

**Comment by westito** [comment]
Thank you! This clock mocking thing much better overall for the entire app. My use case: I'm not rely on device time because it can be inaccurate, so I correct it with sever time.
